// <auto-generated />
namespace TFIP.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CountryList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CountryList));
        
        string IMigrationMetadata.Id
        {
            get { return "201512061738115_CountryList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
